// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: test.proto

package prob

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FakeMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Rfc3339       string                 `protobuf:"bytes,4,opt,name=rfc3339,proto3" json:"rfc3339,omitempty"`
	Unix          int64                  `protobuf:"varint,5,opt,name=unix,proto3" json:"unix,omitempty"`
	Uuid          string                 `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Ran           uint32                 `protobuf:"varint,7,opt,name=ran,proto3" json:"ran,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FakeMessage) Reset() {
	*x = FakeMessage{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FakeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FakeMessage) ProtoMessage() {}

func (x *FakeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FakeMessage.ProtoReflect.Descriptor instead.
func (*FakeMessage) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *FakeMessage) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *FakeMessage) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FakeMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FakeMessage) GetRfc3339() string {
	if x != nil {
		return x.Rfc3339
	}
	return ""
}

func (x *FakeMessage) GetUnix() int64 {
	if x != nil {
		return x.Unix
	}
	return 0
}

func (x *FakeMessage) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *FakeMessage) GetRan() uint32 {
	if x != nil {
		return x.Ran
	}
	return 0
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x04prob\"\xa3\x01\n" +
	"\vFakeMessage\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x18\n" +
	"\arfc3339\x18\x04 \x01(\tR\arfc3339\x12\x12\n" +
	"\x04unix\x18\x05 \x01(\x03R\x04unix\x12\x12\n" +
	"\x04uuid\x18\x06 \x01(\tR\x04uuid\x12\x10\n" +
	"\x03ran\x18\a \x01(\rR\x03ranB\tZ\a../probb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_test_proto_goTypes = []any{
	(*FakeMessage)(nil), // 0: prob.FakeMessage
}
var file_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
